### ISSUE TITLE
Support before hooks

### ISSUE THREAD

**Issue by jutonz** [jutonz/reup#3]
For example, if I add

``` yaml
reindex:
  command: "bundle exec rake es:reindex
```

I should be able to do something like 

``` yaml
serve:
  before:
    - reindex
  command: "bundle exec rails s"
```

**Comment by jutonz** [comment]
Or maybe something like

``` yaml
serve:
  before:
    commands: 
      - echo 'I'm number one!'
    actions:
      - reindex
```

would be better?

It would definitely be more flexible.
