### ISSUE TITLE
Support within-file indicators

### ISSUE THREAD

**Issue by jutonz** [jutonz/reup#4]
For example, I don't want to `foreman start` unless I have `gem "foreman"` in my Gemfile.

Maybe the syntax could look something like this:

``` yaml
rails: 
  indicator_files: 
    Gemfile: 
      includes: foreman
```
